/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @header      libdebug.h
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    Debug functions
 */

#ifndef _LIB_DEBUG_H_
#define _LIB_DEBUG_H_
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/* Definition of the boolean datatype if not enabled */
#ifndef __bool_true_false_are_defined
    #define bool                            _Bool
    #define true                            1
    #define false                           0
    #define __bool_true_false_are_defined   1
#endif

/*!
 * @define      DEBUG
 * @abstract    Outputs a debug message
 * @param       A message, with optional arguments for the format
 */
#define DEBUG( ... ) if( libdebug_is_enabled() == true ) { libdebug_debug( __VA_ARGS__ ); }

/*!
 * @function    libdebug_enable
 * @abstract    Enables the output of debug messages
 * @result      void
 */
void libdebug_enable( void );

/*!
 * @function    libdebug_disable
 * @abstract    Disables the output of debug messages
 * @result      void
 */
void libdebug_disable( void );

/*!
 * @function    libdebug_enable_asl
 * @abstract    Enables the output of debug messages on the Apple System Log facility (Mac OS X only)
 * @result      void
 */
void libdebug_enable_asl( void );

/*!
 * @function    libdebug_disable_asl
 * @abstract    Enables the output of debug messages on the Apple System Log facility (Mac OS X only)
 * @result      void
 */
void libdebug_disable_asl( void );

/*!
 * @function    libdebug_set_exec_name
 * @abstract    Checks if the output of debug messages is enabled
 * @result      True if debug is enabled, otherwise false
 */
bool libdebug_is_enabled( void );

/*!
 * @function    libdebug_set_exec_name
 * @abstract    Sets the name of the main executable (usually argv[ 0 ])
 * @param       name    The executable name
 * @result      void
 * @discussion  On most systems, the name of the executable is automatically
 *              detected, but you can override it by using this function.
 */
void libdebug_set_exec_name( char * name );

/*!
 * @function    libdebug_debug
 * @abstract    Outputs a debug message
 * @param       msg     The debug message
 * @param       ...     Optional arguments for the message
 * @result      void
 * @discussion  Do NOT call this directly. Please use the DEBUG macro instead!
 */
void libdebug_debug( char * msg, ... );

#ifdef __cplusplus
}
#endif

#endif /* _LIB_DEBUG_H_ */
