/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        functions.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    Program's main functions
 */

/* Local includes */
#include "libdebug.h"

/* System includes */
#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/types.h>
#include <sys/time.h>
#include <unistd.h>
#include <pthread.h>

/* Private variables */
static bool   __libdebug_enabled     = false;
static char * __libdebug_exec_name   = NULL;

/* Executable name (implementation-defined) */
char * __progname                    = NULL;
char * program_invocation_short_name = NULL;

/* Weak symbols for the executable name */
extern char * __progname                    __attribute__( ( weak ) );
extern char * program_invocation_short_name __attribute__( ( weak ) );

/*!
 * @function    libdebug_set_exec_name
 * @abstract    Enables the output of debug messages
 * @result      void
 */
void libdebug_enable( void )
{
    __libdebug_enabled = true;
}

/*!
 * @function    libdebug_set_exec_name
 * @abstract    Disables the output of debug messages
 * @result      void
 */
void libdebug_disable( void )
{
    __libdebug_enabled = false;
}

/*!
 * @function    libdebug_set_exec_name
 * @abstract    Checks if the output of debug messages is enabled
 * @result      True if debug is enabled, otherwise false
 */
bool libdebug_is_enabled( void )
{
    return __libdebug_enabled;
}

/*!
 * @function    libdebug_set_exec_name
 * @abstract    Sets the name of the main executable (usually argv[ 0 ])
 * @param       name    The executable name
 * @result      void
 */
void libdebug_set_exec_name( char * name )
{
    int    i;
    size_t length;
    
    __libdebug_exec_name = name;
    length               = strlen( __libdebug_exec_name );
    
    /* Checks the executable path to get only the executable name */
    for( i = length - 1; i > -1; i-- )
    {
        /* Checks for a slash */
        if( __libdebug_exec_name[ i ] == '/' )
        {
            /* Moves the pointer to the file name */
            __libdebug_exec_name += i + 1;
            break;
        }
    }
}

/*!
 * @function    libdebug_debug
 * @abstract    Outputs a debug message
 * @param       msg     The debug message
 * @param       ...     Optional arguments for the message
 * @result      void
 * @discussion  Do NOT call this directly. Please use the DEBUG macro instead!
 */
void libdebug_debug( char * msg, ... )
{
    pid_t          pid;
    pthread_t      tid;
    time_t         t;
    struct tm    * now;
    struct timeval tv;
    va_list        args;
    char           date[ 255 ];
    char         * exec;
    
    /* Mac OS X only - Mach port associated to the thread ID */
    #ifdef __MACH__
    mach_port_t    mid;
    #endif
    
    /* Debug is not enabled - Don't display anything */
    if( __libdebug_enabled == false )
    {
        return;
    }
    
    /* Variable arguments */
    va_start( args, msg );
    
    /* Gets the process and thread IDs */
    pid = getpid();
    tid = pthread_self();
    
    /* Gets the current time informations */
    t   = time( NULL );
    now = localtime( &t );
    gettimeofday( &tv, NULL );
    
    /* Mac OS X only - Gets the Mach port associated to the thread ID */
    #ifdef __MACH__
    mid = pthread_mach_thread_np( tid );
    #endif
    
    /* Formats the date and time */
    memset( ( void * )date, 0, 255 );
    strftime( ( char * )date, 255, "%Y-%m-%d %H:%M:%S", now );
    
    /* Name of the executable */
    if( ( __libdebug_exec_name != NULL ) )
    {
        exec = __libdebug_exec_name;
    }
    else if( __progname != NULL )
    {
        exec = __progname;
    }
    else if( program_invocation_short_name != NULL )
    {
        exec = program_invocation_short_name;
    }
    else
    {
        exec = "unknown";
    }
    
    /* Prints the debug informations line */
    #ifdef __MACH__
    printf( "--- DEBUG > %s.%06lu - %s[%i:%X]: ", date, ( unsigned long )tv.tv_usec, exec, pid, mid );
    #else
    printf( "--- DEBUG > %s.%06lu - %s[%i:%lu]: ", date, ( unsigned long )tv.tv_usec, exec, pid, ( unsigned long )tid );
    #endif
    
    /* Prints the debug message, with arguments */
    vprintf( msg, args );
    printf( "\n" );
    va_end( args );
}
