/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        libprogressbar.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    CLI progress bar functions
 */

/* Local includes */
#include "libprogressbar.h"

/* System includes */
#include <pthread.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>

/* Private variables */
static pthread_t __libprogressbar_thread;
static bool      __libprogressbar_running = false;

/* Private functions' prototypes */
static void * __libprogressbar_update_status( void * args );

/*!
 * 
 */
bool libprogressbar_create_progressbar( unsigned int * percent )
{
    int            rc;
    pthread_attr_t attr;
    
    pthread_attr_init( &attr );
    pthread_attr_setdetachstate( &attr, PTHREAD_CREATE_JOINABLE );
    
    if( __libprogressbar_running == true )
    {
        pthread_join( __libprogressbar_thread, NULL );
    }
    
    rc = pthread_create( &__libprogressbar_thread, &attr, __libprogressbar_update_status, ( void * )percent );
    
    pthread_attr_destroy( &attr );
    
    if( rc != 0 )
    {
        return false;
    }
    
    __libprogressbar_running = true;
    
    return true;
}

/*!
 * 
 */
void libprogressbar_end( void )
{
    if( __libprogressbar_running == true )
    {
        pthread_join( __libprogressbar_thread, NULL );
    }
}

/*!
 * 
 */
void * __libprogressbar_update_status( void * args )
{
    unsigned int        i;
    unsigned int        length;
    unsigned int        percent;
    unsigned int        gear;
    libprogressbar_args arguments;
    bool                complete;
    
    memcpy( &arguments, args, sizeof( libprogressbar_args ) );
    
    length    = arguments.length;
    complete  = false;
    gear      = 0;
    
    for( ; ; )
    {
        percent  = *( arguments.percent );
        complete = ( percent == 100 ) ? true : false;
        gear     = ( gear    == 800 ) ? 0    : gear + 1;
        
        printf( "%s [", arguments.label );
        
        if( percent > 1 )
        {
            for( i = 0; i <= ( ( ( double )length / 100 ) * percent ) - 2; i++ )
            {
                printf( "=" );
            }
            
            printf( ( percent == 100 ) ? "=" : ">" );
        }
        
        for( i = ( ( ( double )length / 100 ) * percent ); i < length; i++ )
        {
            printf( " " );
        }
        
        printf( "]" );
        
        printf( " %3u%% ", percent );
        
        if( complete == false )
        {
            if( gear < 200 )
            {
                printf( "|" );
            }
            else if( gear < 400 )
            {
                printf( "/" );
            }
            else if( gear < 600 )
            {
                printf( "-" );
            }
            else if( gear < 800 )
            {
                printf( "\\" );
            }
        }
        else
        {
            printf( " " );
        }
        
        printf( "\r" );
        fflush( stdout );
        usleep( 1000 );
        
        if( complete == true )
        {
            break;
        }
    }
    
    printf( "\n" );
    
    __libprogressbar_running = false;
    pthread_exit( NULL );
}