/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        args.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    CLI arguments functions
 */

/* Local includes */
#include "egz.h"

/*!
 * 
 */
void egz_get_cli_args( int argc, char ** argv, egz_cli_args * args )
{
    int    i;
    char * option;
    
    /* Default arguments values */
    args->compress    = false;
    args->expand      = false;
    args->force       = false;
    args->version     = false;
    args->help        = false;
    args->debug       = false;
    args->source      = NULL;
    
    i = 0;
    
    /* Process each CLI argument beginning with a '-' */
    while( ++i < argc && ( ( char * )*( ++argv ) )[ 0 ] == '-' )
    {
        /* Checks the next character */
        switch( ( ( char * )*( argv ) )[ 1 ] )
        {
            /* Short form arguments */
            case 'c': args->compress = true; break;
            case 'x': args->expand   = true; break;
            case 'f': args->force    = true; break;
            case 'v': args->version  = true; break;
            case 'h': args->help     = true; break;
            case 'd': args->debug    = true; break;
            
            /* Long form arguments */
            case '-':
                
                /* Gets the argument name */
                option = *( argv ) + 1;
                
                /* Checks the argument name */
                if( strcmp( option, "compress" ) == 0 )
                {
                    args->compress = true;
                }
                else if( strcmp( option, "expand" ) == 0 )
                {
                    args->expand = true;
                }
                else if( strcmp( option, "force" ) == 0 )
                {
                    args->force = true;
                }
                else if( strcmp( option, "version" ) == 0 )
                {
                    args->version = true;
                }
                else if( strcmp( option, "help" ) == 0 )
                {
                    args->help = true;
                }
                else if( strcmp( option, "debug" ) == 0 )
                {
                    args->debug = true;
                }
                
            default:
                
                break;
        }
    }
    
    /* Checks if we still have arguments */
    if( i++ < argc )
    {
        /* Stores the source file */
        args->source = *( argv );
    }
}
