/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        egz.c
 * @copyright   (c) 2011 - Jean-David Gadina - www.xs-labs.com
 * @abstract    Main executable
 */

/* Local includes */
#include "eos-skl/eos-skl.h"
#include "egz.h"

/*!
 * @abstract        main
 * @description     Program's entry point
 * @param           argc    The number of command line arguments
 * @param           argv    An array with the command line arguments
 * @result          The process exit status
 */
int main( int argc, char * argv[] )
{
    egz_status   status;
    FILE       * source;
    FILE       * destination;
    char         destination_filename[ FILENAME_MAX ];
    egz_cli_args args;
    
    /* Processes the command line arguments */
    egz_get_cli_args( argc, argv, &args );
    
    /* Checks if the help dialog must be written */
    if( argc == 1 || args.help == true || ( argc == 2 && args.debug == true ) )
    {
        egz_print_usage( argv[ 0 ] );
        return EXIT_SUCCESS;
    }
    
    /* Checks if the version number must be printed */
    else if( args.version == true )
    {
        egz_print_version( argv[ 0 ] );
        return EXIT_SUCCESS;
    }
    
    /* Enables debug if requested */
    if( args.debug == true )
    {
        libdebug_enable();
    }
    
    /* Prints the command line arguments */
    DEBUG
    (
        "Command line arguments:\n"
        "          - Compress:    %s\n"
        "          - Expand:      %s\n"
        "          - Version:     %s\n"
        "          - Help:        %s\n"
        "          - Debug:       %s\n"
        "          - Source:      %s",
        ( args.compress    == true ) ? "yes"            : "no",
        ( args.expand      == true ) ? "yes"            : "no",
        ( args.force       == true ) ? "yes"            : "no",
        ( args.version     == true ) ? "yes"            : "no",
        ( args.help        == true ) ? "yes"            : "no",
        ( args.debug       == true ) ? "yes"            : "no",
        ( args.source      != NULL ) ? args.source      : "N/A"
    );
    
    DEBUG( "Checking the command line arguments" );
    
    /* Compress and expand options cannot be specified simutaneously */
    if( args.compress == true && args.expand == true )
    {
        ERROR( "-c and -x options cannot be specified simutaneously" );
    }
    
    /* Checks if a source file was specified */
    else if( args.source == NULL )
    {
        ERROR( "No source file specified" );
    }
    
    DEBUG( "Checking the access to the source and destination files" );
    
    /* Checks if the source file exists */
    if( access( args.source, F_OK ) == -1 )
    {
        ERROR( "Source file does not exist: %s", args.source );
    }
    
    /* Checks if the source file is readable */
    if( access( args.source, R_OK ) == -1 )
    {
        ERROR( "Source file is not readable: %s", args.source );
    }
    
    /* Gets the file name for the destination file */
    if( egz_get_destination_filename( args.source, destination_filename, ( args.compress == true ) ? true : false ) == false )
    {
        ERROR( "Cannot determine a destination filename" );
    }
    
    DEBUG( "Destination file name: %s", destination_filename );
    DEBUG( "Opening the file handles" );
    
    /* Opens a file handle to the source file (read) */
    if( NULL == ( source = fopen( args.source, "rb" ) ) )
    {
        ERROR( "Cannot open source file for reading: %s", args.source );
    }
    
    /* Opens a file handle to the destination file (write) */
    if( NULL == ( destination = fopen( destination_filename, "wb+" ) ) )
    {
        fclose( source );
        ERROR( "Cannot open destination file for writing: %s", destination_filename );
    }
    
    /* Checks if the file must be compressed or expanded */
    if( args.compress == true )
    {
        DEBUG( "Entering the compress process" );
        
        /* Compress the source file */
        status = egz_compress( source, destination, args.force );
        
        /* Checks the return status */
        if( status != EGZ_OK )
        {
            DEBUG( "Removing destination file" );
            remove( destination_filename );
            ERROR( "Unable to compress file %s. Reason: %s.", args.source, egz_error_str( status ) );
        }
    }
    else if( args.expand == true )
    {
        DEBUG( "Entering the expand process" );
        
        /* Compress the source file */
        status = egz_expand( source, destination );
        
        /* Checks the return status */
        if( status != EGZ_OK )
        {
            DEBUG( "Removing destination file" );
            remove( destination_filename );
            ERROR( "Unable to expand file %s. Reason: %s.", args.source, egz_error_str( status ) );
        }
    }
    else
    {
        /* Prints the help dialog */
        egz_print_usage( argv[ 0 ] );
        status = false;
    }
    
    DEBUG( "Closing the file handles" );
    fclose( source );
    fclose( destination );
    DEBUG( "Terminating the process" );
    
    return EXIT_SUCCESS;
}
