/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        error.c
 * @copyright   (c) 2011 - Jean-David Gadina - www.xs-labs.com
 * @abstract    Error functions
 */

/* Local includes */
#include "egz.h"

/*!
 * 
 */
void egz_print_usage( char * name )
{
    int    i;
    size_t length;
    
    length = strlen( name );
    
    /* Checks the executable path to get only the executable name */
    for( i = length - 1; i > -1; i-- )
    {
        /* Checks for a slash */
        if( name[ i ] == '/' )
        {
            /* Moves the pointer to the file name */
            name += i + 1;
            break;
        }
    }
    
    printf
    (
        "\n"
        "EGZ - Compression utility (%s)\n"
        "Copyright (c) 2011 XS-Labs - Jean-David Gadina - www.xs-labs.co\n"
        "\n"
        "Usage: %s [OPTIONS] [SOURCE_FILE]\n"
        "\n"
        "Options:\n"
        "    \n"
        "    -c | --compress\n"
        "    Compress SOURCE_FILE\n"
        "    \n"
        "    -x | --expand\n"
        "    Decompress SOURCE_FILE\n"
        "    \n"
        "    -f | --force\n"
        "    Force compression, even if compressed file may be larger\n"
        "    \n"
        "    -h | --help\n"
        "    Print this help message\n"
        "    \n"
        "    -v | --version\n"
        "    Print the version number\n"
        "    \n"
        "    -d | --debug\n"
        "    Print debug informations to stdout\n"
        "\n",
        EGZ_VERSION,
        name
    );
}

/*!
 * 
 */
void egz_print_version( char * name )
{
    printf( "%s version: %s\n", name, EGZ_VERSION );
}
